const meals = [
{ "name":"ผัดคะน้าหมูกรอบ (กับข้าว)","type":"ผัด","calories":420,"protein":18,"fat":32,"carbs":12,"meal":"breakfast","image":"images/b1.jpg"},
{ "name":"กะหล่ำปลีผัดน้ำปลา (กับข้าว)","type":"ผัด","calories":180,"protein":4,"fat":10,"carbs":18,"meal":"breakfast","image":"images/b2.jpg"},
{ "name":"ผัดผักรวม (กับข้าว)","type":"ผัด","calories":220,"protein":6,"fat":12,"carbs":20,"meal":"breakfast","image":"images/b3.jpg"},
{ "name":"บวบผัดไข่ (กับข้าว)","type":"ผัด","calories":250,"protein":10,"fat":18,"carbs":10,"meal":"breakfast","image":"images/b4.jpg"},
{ "name":"ผัดกะเพราหมูสับ (กับข้าว)","type":"ผัด","calories":380,"protein":22,"fat":28,"carbs":8,"meal":"breakfast","image":"images/b5.jpg"},
{ "name":"เห็ดผัดน้ำมันหอย (กับข้าว)","type":"ผัด","calories":200,"protein":6,"fat":14,"carbs":12,"meal":"breakfast","image":"images/b6.jpg"},
{ "name":"หมูผัดขิง (กับข้าว)","type":"ผัด","calories":340,"protein":20,"fat":22,"carbs":14,"meal":"breakfast","image":"images/b7.jpg"},
{ "name":"โจ๊กหมู","type":"ต้ม","calories":250,"protein":14,"fat":6,"carbs":32,"meal":"breakfast","image":"images/b8.jpg"},
{ "name":"ไข่พะโล้ (กับข้าว)","type":"ต้ม","calories":300,"protein":16,"fat":20,"carbs":12,"meal":"breakfast","image":"images/b9.jpg"},
{ "name":"ต้มจืดเต้าหู้หมูสับ (กับข้าว)","type":"ต้ม","calories":180,"protein":15,"fat":8,"carbs":6,"meal":"breakfast","image":"images/b10.jpg"},
{ "name":"ต้มจืดกะหล่ำปลีวุ้นเส้น (กับข้าว)","type":"ต้ม","calories":200,"protein":9,"fat":7,"carbs":22,"meal":"breakfast","image":"images/b11.jpg"},
{ "name":"แกงจืดมะระยัดไส้ (กับข้าว)","type":"ต้ม","calories":220,"protein":18,"fat":10,"carbs":8,"meal":"breakfast","image":"images/b12.jpg"},
{ "name":"ต้มไชเท้ากระดูกหมู (กับข้าว)","type":"ต้ม","calories":260,"protein":20,"fat":14,"carbs":10,"meal":"breakfast","image":"images/b13.jpg"},
{ "name":"ต้มวุ้นเส้นหมูสับ (กับข้าว)","type":"ต้ม","calories":230,"protein":14,"fat":9,"carbs":24,"meal":"breakfast","image":"images/b14.jpg"},
{ "name":"หมูปิ้ง (กับข้าว)","type":"ย่าง","calories":190,"protein":12,"fat":9,"carbs":14,"meal":"breakfast","image":"images/b15.jpg"},
{ "name":"ไก่ย่าง (กับข้าว)","type":"ย่าง","calories":280,"protein":30,"fat":16,"carbs":2,"meal":"breakfast","image":"images/b16.jpg"},
{ "name":"คอหมูย่าง (กับข้าว)","type":"ย่าง","calories":420,"protein":22,"fat":35,"carbs":4,"meal":"breakfast","image":"images/b17.jpg"},
{ "name":"ปลานิลย่าง (กับข้าว)","type":"ย่าง","calories":250,"protein":32,"fat":10,"carbs":0,"meal":"breakfast","image":"images/b18.jpg"},
{ "name":"ไส้กรอกอีสานย่าง","type":"ย่าง","calories":300,"protein":14,"fat":18,"carbs":22,"meal":"breakfast","image":"images/b19.jpg"},
{ "name":"เต้าหู้ย่าง (กับข้าว)","type":"ย่าง","calories":180,"protein":12,"fat":9,"carbs":10,"meal":"breakfast","image":"images/b20.jpg"},
{ "name":"เนื้อย่าง (กับข้าว)","type":"ย่าง","calories":320,"protein":28,"fat":22,"carbs":0,"meal":"breakfast","image":"images/b21.jpg"},
{ "name":"ไข่เจียว (กับข้าว)","type":"ทอด","calories":215,"protein":12,"fat":18,"carbs":2,"meal":"breakfast","image":"images/b22.jpg"},
{ "name":"ไข่ดาว (กับข้าว)","type":"ทอด","calories":160,"protein":7,"fat":14,"carbs":1,"meal":"breakfast","image":"images/b23.jpg"},
{ "name":"หมูสามชั้นทอด (กับข้าว)","type":"ทอด","calories":480,"protein":18,"fat":45,"carbs":2,"meal":"breakfast","image":"images/b24.jpg"},
{ "name":"กุนเชียงทอด (กับข้าว)","type":"ทอด","calories":300,"protein":9,"fat":22,"carbs":18,"meal":"breakfast","image":"images/b25.jpg"},
{ "name":"เต้าหู้ทอด (กับข้าว)","type":"ทอด","calories":250,"protein":12,"fat":18,"carbs":12,"meal":"breakfast","image":"images/b26.jpg"},
{ "name":"ปลาทอดน้ำปลา (กับข้าว)","type":"ทอด","calories":330,"protein":28,"fat":22,"carbs":4,"meal":"breakfast","image":"images/b27.jpg"},
{ "name":"ปีกไก่ทอด (กับข้าว)","type":"ทอด","calories":340,"protein":26,"fat":24,"carbs":6,"meal":"breakfast","image":"images/b28.jpg"},
{ "name":"ไข่ตุ๋น (กับข้าว)","type":"นึ่ง","calories":140,"protein":12,"fat":8,"carbs":3,"meal":"breakfast","image":"images/b29.jpg"},
{ "name":"หมูสับนึ่งปลาเค็ม (กับข้าว)","type":"นึ่ง","calories":260,"protein":22,"fat":16,"carbs":6,"meal":"breakfast","image":"images/b30.jpg"},
{ "name":"กุ้งนึ่งวุ้นเส้น (กับข้าว)","type":"นึ่ง","calories":300,"protein":24,"fat":8,"carbs":34,"meal":"breakfast","image":"images/b31.jpg"},
{ "name":"ไก่นึ่งสมุนไพร (กับข้าว)","type":"นึ่ง","calories":240,"protein":32,"fat":10,"carbs":4,"meal":"breakfast","image":"images/b32.jpg"},
{ "name":"ปลานึ่งซีอิ๊ว (กับข้าว)","type":"นึ่ง","calories":220,"protein":30,"fat":8,"carbs":6,"meal":"breakfast","image":"images/b33.jpg"},
{ "name":"กะหล่ำปลียัดไส้นึ่ง (กับข้าว)","type":"นึ่ง","calories":210,"protein":14,"fat":10,"carbs":12,"meal":"breakfast","image":"images/b34.jpg"},
{ "name":"เต้าหู้นึ่งหมูสับ (กับข้าว)","type":"นึ่ง","calories":190,"protein":18,"fat":9,"carbs":8,"meal":"breakfast","image":"images/b35.jpg"},
{ "name":"ไก่ผัดเม็ดมะม่วง (กับข้าว)","type":"ผัด","calories":420,"protein":28,"fat":26,"carbs":18,"meal":"lunch","image":"images/l1.jpg"},
{ "name":"ผัดพริกขิงหมู (กับข้าว)","type":"ผัด","calories":390,"protein":24,"fat":28,"carbs":10,"meal":"lunch","image":"images/l2.jpg"},
{ "name":"กุ้งผัดพริกเผา (กับข้าว)","type":"ผัด","calories":360,"protein":26,"fat":20,"carbs":16,"meal":"lunch","image":"images/l3.jpg"},
{ "name":"ผัดผักบุ้งไฟแดง (กับข้าว)","type":"ผัด","calories":200,"protein":6,"fat":12,"carbs":16,"meal":"lunch","image":"images/l4.jpg"},
{ "name":"ผัดวุ้นเส้นกุ้ง (กับข้าว)","type":"ผัด","calories":380,"protein":20,"fat":14,"carbs":48,"meal":"lunch","image":"images/l5.jpg"},
{ "name":"ผัดทะเลรวม (กับข้าว)","type":"ผัด","calories":340,"protein":30,"fat":16,"carbs":12,"meal":"lunch","image":"images/l6.jpg"},
{ "name":"ต้มยำกุ้ง (กับข้าว)","type":"ต้ม","calories":280,"protein":24,"fat":14,"carbs":8,"meal":"lunch","image":"images/l7.jpg"},
{ "name":"ต้มข่าไก่ (กับข้าว)","type":"ต้ม","calories":350,"protein":26,"fat":24,"carbs":10,"meal":"lunch","image":"images/l8.jpg"},
{ "name":"ก๋วยเตี๋ยว","type":"ต้ม","calories":380,"protein":18,"fat":10,"carbs":55,"meal":"lunch","image":"images/l9.jpg"},
{ "name":"ต้มแซ่บกระดูกหมู (กับข้าว)","type":"ต้ม","calories":320,"protein":28,"fat":18,"carbs":6,"meal":"lunch","image":"images/l10.jpg"},
{ "name":"ข้าวขาหมู","type":"ต้ม","calories":690,"protein":28,"fat":38,"carbs":60,"meal":"lunch","image":"images/l11.jpg"},
{ "name":"ข้าวมันไก่","type":"ต้ม","calories":620,"protein":32,"fat":20,"carbs":75,"meal":"lunch","image":"images/l12.jpg"},
{ "name":"ซี่โครงหมูย่าง (กับข้าว)","type":"ย่าง","calories":480,"protein":32,"fat":36,"carbs":6,"meal":"lunch","image":"images/l13.jpg"},
{ "name":"สะโพกไก่ย่าง (กับข้าว)","type":"ย่าง","calories":420,"protein":34,"fat":30,"carbs":2,"meal":"lunch","image":"images/l14.jpg"},
{ "name":"ปลาหมึกย่าง (กับข้าว)","type":"ย่าง","calories":220,"protein":28,"fat":4,"carbs":6,"meal":"lunch","image":"images/l15.jpg"},
{ "name":"เนื้อบริสเก็ตย่าง (กับข้าว)","type":"ย่าง","calories":460,"protein":38,"fat":34,"carbs":0,"meal":"lunch","image":"images/l16.jpg"},
{ "name":"กุ้งแม่น้ำย่าง (กับข้าว)","type":"ย่าง","calories":300,"protein":26,"fat":20,"carbs":2,"meal":"lunch","image":"images/l17.jpg"},
{ "name":"ปลาดุกย่าง (กับข้าว)","type":"ย่าง","calories":350,"protein":30,"fat":24,"carbs":0,"meal":"lunch","image":"images/l18.jpg"},
{ "name":"หมูทอดกระเทียม (กับข้าว)","type":"ทอด","calories":420,"protein":30,"fat":30,"carbs":8,"meal":"lunch","image":"images/l19.jpg"},
{ "name":"ปลานิลทอด (กับข้าว)","type":"ทอด","calories":400,"protein":34,"fat":28,"carbs":4,"meal":"lunch","image":"images/l20.jpg"},
{ "name":"ไก่ทอดกรอบ (กับข้าว)","type":"ทอด","calories":520,"protein":32,"fat":36,"carbs":20,"meal":"lunch","image":"images/l21.jpg"},
{ "name":"กุ้งชุบแป้งทอด (กับข้าว)","type":"ทอด","calories":450,"protein":18,"fat":28,"carbs":36,"meal":"lunch","image":"images/l22.jpg"},
{ "name":"ซี่โครงหมูทอดกระเทียม (กับข้าว)","type":"ทอด","calories":480,"protein":28,"fat":38,"carbs":6,"meal":"lunch","image":"images/l23.jpg"},
{ "name":"ทอดมันปลา (กับข้าว)","type":"ทอด","calories":350,"protein":22,"fat":24,"carbs":12,"meal":"lunch","image":"images/l24.jpg"},
{ "name":"ลาบหมู (กับข้าว)","type":"ยำ","calories":280,"protein":22,"fat":18,"carbs":6,"meal":"lunch","image":"images/l25.jpg"},
{ "name":"ยำวุ้นเส้น","type":"ยำ","calories":300,"protein":18,"fat":10,"carbs":40,"meal":"lunch","image":"images/l26.jpg"},
{ "name":"ยำเนื้อย่าง (กับข้าว)","type":"ยำ","calories":360,"protein":28,"fat":22,"carbs":8,"meal":"lunch","image":"images/l27.jpg"},
{ "name":"ยำกุ้งสด","type":"ยำ","calories":240,"protein":24,"fat":8,"carbs":10,"meal":"lunch","image":"images/l28.jpg"},
{ "name":"ยำปลาดุกฟู","type":"ยำ","calories":420,"protein":24,"fat":30,"carbs":18,"meal":"lunch","image":"images/l29.jpg"},
{ "name":"ปูนึ่งวุ้นเส้น (กับข้าว)","type":"นึ่ง","calories":380,"protein":34,"fat":12,"carbs":36,"meal":"lunch","image":"images/l30.jpg"},
{ "name":"ไก่นึ่งซีอิ๊ว (กับข้าว)","type":"นึ่ง","calories":260,"protein":32,"fat":12,"carbs":6,"meal":"lunch","image":"images/l31.jpg"},
{ "name":"ปลานึ่งมะนาว (กับข้าว)","type":"นึ่ง","calories":230,"protein":30,"fat":8,"carbs":8,"meal":"lunch","image":"images/l32.jpg"},
{ "name":"ซี่โครงหมูนึ่งเต้าซี่ (กับข้าว)","type":"นึ่ง","calories":340,"protein":26,"fat":22,"carbs":10,"meal":"lunch","image":"images/l33.jpg"},
{ "name":"หอยแมลงภู่นึ่ง","type":"นึ่ง","calories":220,"protein":26,"fat":6,"carbs":8,"meal":"lunch","image":"images/l34.jpg"},
{ "name":"เต้าหู้ไข่นึ่งทะเล","type":"นึ่ง","calories":300,"protein":20,"fat":18,"carbs":14,"meal":"lunch","image":"images/l35.jpg"},
{ "name":"ฟักทองผัดไข่ (กับข้าว)","type":"ผัด","calories":270,"protein":10,"fat":16,"carbs":22,"meal":"dinner","image":"images/d1.jpg"},
{ "name":"หมูผัดกะปิ (กับข้าว)","type":"ผัด","calories":390,"protein":24,"fat":28,"carbs":10,"meal":"dinner","image":"images/d2.jpg"},
{ "name":"ผัดเห็ดรวม (กับข้าว)","type":"ผัด","calories":210,"protein":8,"fat":12,"carbs":16,"meal":"dinner","image":"images/d3.jpg"},
{ "name":"มะระผัดไข่ (กับข้าว)","type":"ผัด","calories":240,"protein":12,"fat":14,"carbs":14,"meal":"dinner","image":"images/d4.jpg"},
{ "name":"ไก่คั่วพริกเกลือ (กับข้าว)","type":"ผัด","calories":420,"protein":30,"fat":30,"carbs":8,"meal":"dinner","image":"images/d5.jpg"},
{ "name":"แกงจืดลูกชิ้นปลา (กับข้าว)","type":"ต้ม","calories":190,"protein":16,"fat":6,"carbs":10,"meal":"dinner","image":"images/d6.jpg"},
{ "name":"ต้มฟักกระดูกหมู (กับข้าว)","type":"ต้ม","calories":260,"protein":20,"fat":14,"carbs":12,"meal":"dinner","image":"images/d7.jpg"},
{ "name":"ต้มเส้นหมี่ไก่ฉีก","type":"ต้ม","calories":280,"protein":22,"fat":8,"carbs":38,"meal":"dinner","image":"images/d8.jpg"},
{ "name":"แกงหน่อไม้ (กับข้าว)","type":"ต้ม","calories":220,"protein":14,"fat":10,"carbs":18,"meal":"dinner","image":"images/d9.jpg"},
{ "name":"เกี๊ยวน้ำหมู","type":"ต้ม","calories":560,"protein":26,"fat":18,"carbs":72,"meal":"dinner","image":"images/d10.jpg"},
{ "name":"แซลมอนย่าง","type":"ย่าง","calories":360,"protein":34,"fat":24,"carbs":0,"meal":"dinner","image":"images/d11.jpg"},
{ "name":"สามชั้นย่าง","type":"ย่าง","calories":520,"protein":20,"fat":48,"carbs":2,"meal":"dinner","image":"images/d12.jpg"},
{ "name":"เป็ดย่าง","type":"ย่าง","calories":780,"protein":40,"fat":42,"carbs":65,"meal":"dinner","image":"images/d13.jpg"},
{ "name":"มะเขือย่าง","type":"ย่าง","calories":120,"protein":4,"fat":6,"carbs":16,"meal":"dinner","image":"images/d14.jpg"},
{ "name":"ตับไก่ย่าง","type":"ย่าง","calories":220,"protein":26,"fat":12,"carbs":4,"meal":"dinner","image":"images/d15.jpg"},
{ "name":"หมูกรอบทอด","type":"ทอด","calories":550,"protein":22,"fat":48,"carbs":4,"meal":"dinner","image":"images/d16.jpg"},
{ "name":"ปลาหมึกทอดกระเทียม (กับข้าว)","type":"ทอด","calories":420,"protein":30,"fat":26,"carbs":12,"meal":"dinner","image":"images/d17.jpg"},
{ "name":"ปลาทูทอด (กับข้าว)","type":"ทอด","calories":300,"protein":24,"fat":22,"carbs":0,"meal":"dinner","image":"images/d18.jpg"},
{ "name":"เห็ดเข็มทองทอดกรอบ","type":"ทอด","calories":350,"protein":8,"fat":22,"carbs":36,"meal":"dinner","image":"images/d19.jpg"},
{ "name":"เต้าหู้ทอดกระเทียม","type":"ทอด","calories":280,"protein":14,"fat":20,"carbs":14,"meal":"dinner","image":"images/d20.jpg"},
{ "name":"ยำทะเล","type":"ยำ","calories":300,"protein":28,"fat":10,"carbs":14,"meal":"dinner","image":"images/d21.jpg"},
{ "name":"ยำไข่เยี่ยวม้า","type":"ยำ","calories":260,"protein":16,"fat":18,"carbs":8,"meal":"dinner","image":"images/d22.jpg"},
{ "name":"ยำหมูย่าง","type":"ยำ","calories":340,"protein":26,"fat":20,"carbs":12,"meal":"dinner","image":"images/d23.jpg"},
{ "name":"ยำผักบุ้งกรอบ","type":"ยำ","calories":380,"protein":10,"fat":22,"carbs":38,"meal":"dinner","image":"images/d24.jpg"},
{ "name":"ยำไข่เค็ม","type":"ยำ","calories":240,"protein":12,"fat":18,"carbs":10,"meal":"dinner","image":"images/d25.jpg"},
{ "name":"ห่อหมกทะเล","type":"นึ่ง","calories":350,"protein":26,"fat":24,"carbs":12,"meal":"dinner","image":"images/d26.jpg"},
{ "name":"กุ้งนึ่งกระเทียม","type":"นึ่ง","calories":260,"protein":28,"fat":10,"carbs":6,"meal":"dinner","image":"images/d27.jpg"},
{ "name":"อกไก่นึ่ง","type":"นึ่ง","calories":210,"protein":36,"fat":4,"carbs":0,"meal":"dinner","image":"images/d28.jpg"},
{ "name":"ห่อหมกปลานึ่ง (กับข้าว)","type":"นึ่ง","calories":320,"protein":24,"fat":22,"carbs":10,"meal":"dinner","image":"images/d29.jpg"},
{ "name":"เห็ดนึ่งซีอิ๊ว","type":"นึ่ง","calories":150,"protein":8,"fat":6,"carbs":14,"meal":"dinner","image":"images/d30.jpg"}
];